openapi: '3.0.2'
info:
  title: Dogr Backend API
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /images:
    get:
      responses:
        '200':
          description: OK
        '404':
          description: NOT FOUND
    post:
      responses:
        '200':
          description: OK
        '400':
          description: BAD REQUEST
  /images/:id:
    get:
      responses:
        '200':
          description: OK
        '400':
          description: BAD REQUEST
        '404':
          description: NOT FOUND
    delete:
      responses:
        '204':
          description: DELETED
        '400':
          description: BAD REQUEST
